/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class RecommendationAppTest {

    @Test void appHasAGreeting() {
        RecommendationApp classUnderTest = new RecommendationApp();
       assertNotNull(classUnderTest, "RecommendationApp should be instantiated");
    }
}



